run:
  tests: false

linters:
  enable:
    - revive

issues:
  exclude-rules:
    - linters:
        - govet
      text: "OperationOutcome"
    - linters:
        - golint
        - revive
      text: "type name will be used"
