// Code generated by "stringer -type=CancellationReason -output=cancellation_reason_string.go"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-1]
	_ = x[EndOfStream-2]
	_ = x[CancelledByUser-3]
}

const _CancellationReason_name = "ErrorEndOfStreamCancelledByUser"

var _CancellationReason_index = [...]uint8{0, 5, 16, 31}

func (i CancellationReason) String() string {
	i -= 1
	if i < 0 || i >= CancellationReason(len(_CancellationReason_index)-1) {
		return "CancellationReason(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CancellationReason_name[_CancellationReason_index[i]:_CancellationReason_index[i+1]]
}
