// Code generated by "stringer -type=StreamStatus -trimprefix=StreamStatus -output=stream_status_string.go"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StreamStatusUnknown-0]
	_ = x[StreamStatusNoData-1]
	_ = x[StreamStatusPartialData-2]
	_ = x[StreamStatusAllData-3]
	_ = x[StreamStatusCanceled-4]
}

const _StreamStatus_name = "UnknownNoDataPartialDataAllDataCanceled"

var _StreamStatus_index = [...]uint8{0, 7, 13, 24, 31, 39}

func (i StreamStatus) String() string {
	if i < 0 || i >= StreamStatus(len(_StreamStatus_index)-1) {
		return "StreamStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StreamStatus_name[_StreamStatus_index[i]:_StreamStatus_index[i+1]]
}
