#!/usr/bin/env bash
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE.md file in the project root for full license information.
#
# Loads test secrets from the subscriptions JSON file generated by
# generate-subscription-file.yml and exports the environment variables
# required by the Go test suite.
#
# Usage:
#   source ci/load-build-secrets.sh
#
# The script expects the JSON at $BUILD_SOURCESDIRECTORY/secrets/test.subscriptions.regions.json
# (set by Azure DevOps) or falls back to ./secrets/test.subscriptions.regions.json.

set -euo pipefail

# CRITICAL: Disable trace mode before handling secrets. If the caller
# had 'set -x' enabled (e.g. for debugging), bash would echo every
# variable assignment — including the subscription key — to stderr
# before global_redact is available to filter it.
set +x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SECRETS_DIR="${BUILD_SOURCESDIRECTORY:-$REPO_ROOT}/secrets"
SUBSCRIPTIONS_FILE="$SECRETS_DIR/test.subscriptions.regions.json"

if [[ ! -f "$SUBSCRIPTIONS_FILE" ]]; then
  echo "ERROR: Subscriptions JSON not found at $SUBSCRIPTIONS_FILE"
  echo "Run the generate-subscription-file.yml step first."
  exit 1
fi

# Require jq
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required but not installed."
  exit 1
fi

# Extract speech subscription key and region
export SPEECH_SUBSCRIPTION_KEY=$(jq -jr '.UnifiedSpeechSubscription.Key' "$SUBSCRIPTIONS_FILE")
export SPEECH_SUBSCRIPTION_REGION=$(jq -jr '.UnifiedSpeechSubscription.Region' "$SUBSCRIPTIONS_FILE")

if [[ -z "$SPEECH_SUBSCRIPTION_KEY" || "$SPEECH_SUBSCRIPTION_KEY" == "null" ]]; then
  echo "ERROR: Failed to extract UnifiedSpeechSubscription.Key from $SUBSCRIPTIONS_FILE"
  exit 1
fi

if [[ -z "$SPEECH_SUBSCRIPTION_REGION" || "$SPEECH_SUBSCRIPTION_REGION" == "null" ]]; then
  echo "ERROR: Failed to extract UnifiedSpeechSubscription.Region from $SUBSCRIPTIONS_FILE"
  exit 1
fi

echo "Loaded speech subscription for region: $SPEECH_SUBSCRIPTION_REGION"

# --- Redaction helpers (prevent secrets from leaking in CI logs) ---

GLOBAL_STRINGS_TO_REDACT=(
  "$SPEECH_SUBSCRIPTION_KEY"
)

URL_ENCODED_SPEECH_SUBSCRIPTION_KEY=$(jq -nr --arg v "$SPEECH_SUBSCRIPTION_KEY" '$v | @uri')
if [[ -n "$URL_ENCODED_SPEECH_SUBSCRIPTION_KEY" && "$URL_ENCODED_SPEECH_SUBSCRIPTION_KEY" != "$SPEECH_SUBSCRIPTION_KEY" ]]; then
  GLOBAL_STRINGS_TO_REDACT+=("$URL_ENCODED_SPEECH_SUBSCRIPTION_KEY")
fi
unset URL_ENCODED_SPEECH_SUBSCRIPTION_KEY

redact_input_with() {
  # Redacts known sensitive strings from stdin.
  # Avoids repeated invocation overhead by using perl streaming.
  perl -MIO::Handle -lpe \
    'BEGIN {
       STDOUT->autoflush(1);
       STDERR->autoflush(1);
       if (@ARGV) {
         $re = sprintf "(?:%s)", (join "|", map { quotemeta $_ } splice @ARGV);
         $re = qr/$re/
       }
     }
     $re and s/$re/***/gi' "$@"
}

global_redact() {
  redact_input_with "${GLOBAL_STRINGS_TO_REDACT[@]}"
}

export -f redact_input_with
export -f global_redact
