name: Lint code
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
env:
  CARBON_VERSION: "1.51.1"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Get Carbon
        run: |
          mkdir /tmp/carbon
          pushd /tmp/carbon
          wget https://csspeechstorage.blob.core.windows.net/drop/$CARBON_VERSION/SpeechSDK-Linux-$CARBON_VERSION.tar.gz
          tar xzf SpeechSDK-Linux-$CARBON_VERSION.tar.gz
          rm SpeechSDK-Linux-$CARBON_VERSION.tar.gz
          ln -s SpeechSDK-Linux-$CARBON_VERSION current
          popd
      - name: golangci-lint
        uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5.3.0
        env:
          CGO_CFLAGS: "-I/tmp/carbon/current/include/c_api"
          CGO_LDFLAGS: "-L/tmp/carbon/current/lib/x64 -lMicrosoft.CognitiveServices.Speech.core"
